version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - redis
      - elasticsearch
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:latest
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: laravel_elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - laravel_network

  composer:
    image: composer:2
    container_name: laravel_composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    command: tail -f /dev/null

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
