name: Deploy to Kubernetes

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Kodu Klonla
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker Hub'a Bağlan
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Docker İmajı Oluştur ve Push Et
    - name: Build and Push Docker Image
      run: |
        docker build -t rampesna/laravelAllTechs:${{ github.ref_name }} .
        docker push rampesna/laravelAllTechs:${{ github.ref_name }}

    # 4. Kubernetes'e Dağıt
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/laravelAllTechs \
          laravel_app=rampesna/laravelAllTechs:${{ github.ref_name }}
